name: Kernel CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Prerequisites
      run: |
        sudo apt-get install build-essential bison flex libgmp3-dev libmpc-dev libmpfr-dev automake autogen
    - name: Build Toolchain
      run: |
        cd kernel
        bash utils/build-toolchain.sh
    - name: Build Kernel
      run: |
        cd kernel
        make
